// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysProgLab3.Models;

#nullable disable

namespace SysProgLab3.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SysProgLab3.Models.AccountingGoods", b =>
                {
                    b.Property<long>("IDCounting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDCounting"));

                    b.Property<long>("CodeGood")
                        .HasColumnType("bigint");

                    b.Property<int>("CountOfSold")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfSale")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PriceCurantCodeGood")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceGood")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDCounting");

                    b.HasIndex("PriceCurantCodeGood");

                    b.ToTable("AccountingGoods");
                });

            modelBuilder.Entity("SysProgLab3.Models.MyUser", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUser"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("MyUsers");
                });

            modelBuilder.Entity("SysProgLab3.Models.PriceCurant", b =>
                {
                    b.Property<long>("CodeGood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CodeGood"));

                    b.Property<string>("NameGood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceGood")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodeGood");

                    b.ToTable("PriceCurants");
                });

            modelBuilder.Entity("SysProgLab3.Models.AccountingGoods", b =>
                {
                    b.HasOne("SysProgLab3.Models.PriceCurant", "PriceCurant")
                        .WithMany()
                        .HasForeignKey("PriceCurantCodeGood");

                    b.Navigation("PriceCurant");
                });
#pragma warning restore 612, 618
        }
    }
}
